package com.dsource.idc.jellow.Models;

/**
 * Created by ekalpa on 6/21/2017.
 */

public class LayerOneSpeech {

    public String[][] getLayerOneSpeechEnglish(){
        return layerOneSpeechEnglish;
    }
    public String[][] getLayerOneSpeechHindi(){
        return layerOneSpeechHindi;
    }

    private final String[][] layerOneSpeechHindi = {{
            "मुझे लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात करना अच्छा लगता हैं ",
            "मुझे सच में लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात करना अच्छा लगता हैं",
            "मुझे लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात करनी हैं",
            "मुझे सच में लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात करनी हैं",
            "मुझे लोगों को नमस्कार करना और अपनी भावनाओं के बारे में और ज़्यादा बात करनी हैं",
            "मुझे सच में लोगों को नमस्कार करना और अपनी भावनाओं के बारे में और ज़्यादा बात करनी हैं",
            "मुझे लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात करना अच्छा नहीं लगता हैं",
            "मुझे सच में लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात करना अच्छा नहीं लगता हैं",
            "मुझे लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात नहीं करनी हैं",
            "मुझे सच में लोगों को नमस्कार करना और अपनी भावनाओं के बारे में बात नहीं करनी हैं",
            "मुझे लोगों को नमस्कार करना और अपनी भावनाओं के बारे में कुछ भी बात नहीं करनी हैं",
            "मुझे सच में लोगों को नमस्कार करना और अपनी भावनाओं के बारे में कुछ भी बात नहीं करनी हैं"
    }, {"मुझे अपने रोज़़ के काम करना अच्छा लगता हैं",
            "मुझे सच में अपने रोज़ के काम करना अच्छा लगता हैं",
            "मुझे अपने रोज़ के काम करने हैं",
            "मुझे सच में अपने रोज़ के काम करने हैं",
            "मुझे अपने रोज़ के काम पर ज़्यादा समय बिताना हैं",
            "मुझे सच में अपने रोज़ के काम पर और ज़्यादा समय बिताना हैं",
            "मुझे अपने रोज़ के काम करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने रोज़ के काम करना अच्छा नहीं लगता हैं",
            "मुझे अपने रोज़ के काम नहीं करने हैं",
            "मुझे सच में अपने रोज़ के काम नहीं करने हैं",
            "मुझे अपने रोज़ के काम पर ज़्यादा समय नहीं बिताना हैं",
            "मुझे सच में अपने रोज़ के काम पर कुछ भी समय नहीं बिताना हैं"
    }, {"मुझे खाना अच्छा लगता हैं",
            "मुझे सच में खाना अच्छा लगता हैं",
            "मुझे खाना हैं",
            "मुझे सच में खाना हैं",
            "मुझे थोड़ा और खाना हैं",
            "मुझे सच में थोड़ा और खाना हैं",
            "मुझे खाना अच्छा नहीं लगता हैं",
            "मुझे सच में खाना अच्छा नहीं लगता हैं",
            "मुझे खाना नहीं हैं",
            "मुझे सच में खाना नहीं हैं",
            "मुझे कुछ भी खाना नहीं हैं",
            "मुझे सच में कुछ भी खाना नहीं हैं"
    }, {"मुझे मज़े करना अच्छा लगता हैं",
            "मुझे सच में मज़े करना अच्छा लगता हैं",
            "मुझे मज़े करने हैं",
            "मुझे सच में मज़े करने हैं",
            "मुझे और मज़े करने हैं",
            "मुझे सच में और ज़्यादा मज़े करने हैं",
            "मुझे मज़े करना अच्छा नहीं लगता हैं",
            "मुझे सच में मज़े करना अच्छा नहीं लगता हैं",
            "मुझे मज़े नहीं करने हैं",
            "मुझे सच में मज़े नहीं करने हैं",
            "मुझे और मज़े नहीं करने हैं",
            "मुझे सच में और मज़े नहीं करने हैं"
    }, {"मुझे सीखना अच्छा लगता हैं",
            "मुझे सच में सीखना अच्छा लगता हैं",
            "मुझे सीखना हैं",
            "मुझे सच में सीखना हैं",
            "मुझे और सीखना हैं",
            "मुझे थोड़ा और सीखना हैं",
            "मुझे सीखना अच्छा नहीं लगता हैं",
            "मुझे सच में सीखना अच्छा नहीं लगता हैं",
            "मुझे सीखना नहीं हैं",
            "मुझे सच में सीखना नहीं हैं",
            "मुझे और सीखना नहीं हैं",
            "मुझे सच में और सीखना  नहीं हैं"
    }, {"मुझे लोगों से बात करना अच्छा लगता हैं",
            "मुझे सच में लोगों से बात करना अच्छा लगता हैं",
            "मुझे लोगों से मिलना हैं",
            "मुझे सच में लोगों से मिलना हैं",
            "मुझे कुछ और लोगों से मिलना हैं",
            "मुझे सच में कुछ और लोगों से मिलना हैं",
            "मुझे लोगों से बात करना अच्छा नहीं लगता हैं",
            "मुझे सच में लोगों से बात करना अच्छा नहीं लगता हैं",
            "मुझे लोगों से नहीं मिलना हैं",
            "मुझे सच में लोगों से नहीं मिलना हैं",
            "मुझे किसी से भी नहीं मिलना हैं",
            "मुझे सच में किसी से भी नहीं मिलना हैं"
    }, {"मुझे जगहों को देखना अच्छा लगता हैं",
            "मुझे सच में जगहों को देखना अच्छा लगता हैं",
            "मुझे अलग-अलग जगहों को देखना हैं",
            "मुझे सच में अलग-अलग जगहों को देखना हैं",
            "मुझे कुछ और जगहों को देखना हैं",
            "मुझे सच में कुछ और जगहों को देखना हैं",
            "मुझे जगहों को देखना अच्छा नहीं लगता हैं",
            "मुझे सच में जगहों को देखना अच्छा नहीं लगता हैं",
            "मुझे अलग-अलग जगहों को नहीं देखना हैं",
            "मुझे सच में अलग-अलग जगहों को नहीं देखना हैं",
            "मुझे और जगहों को नहीं देखना हैं",
            "मुझे सच में और जगहों को नहीं देखना हैं"
    }, {"मुझे समय और मौसम के बारे में बात करना अच्छा लगता हैं",
            "मुझे सच में समय और मौसम के बारे में बात करना अच्छा लगता हैं",
            "मुझे समय और मौसम के बारे में बात करनी  हैं",
            "मुझे सच में समय और मौसम के बारे में बात करनी हैं",
            "मुझे समय और मौसम के बारे में और ज़्यादा बात करनी  हैं",
            "मुझे सच में समय और मौसम के बारे में और ज़्यादा बात करनी हैं",
            "मुझे समय और मौसम के बारे में बात करना अच्छा नहीं लगता हैं",
            "मुझे सच में समय और मौसम के बारे में बात करना अच्छा नहीं लगता हैं",
            "मुझे समय और मौसम के बारे में बात नहीं करनी हैं",
            "मुझे  सच में समय और मौसम के बारे में बात नहीं करनी हैं",
            "मुझे समय और मौसम के बारे में कुछ भी बात नहीं करनी हैं",
            "मुझे सच में समय और मौसम के बारे में कुछ भी बात नहीं करनी हैं"
    }, {"मुझे मदद करना अच्छा लगता हैं",
            "मुझे सच में मदद करना अच्छा लगता हैं",
            "मुझे मदद की ज़रूरत हैं",
            "मुझे सच में मदद की ज़रूरत हैं",
            "मुझे और मदद की ज़रूरत हैं",
            "मुझे  सच में और ज़्यादा मदद की ज़रूरत है",
            "मुझे मदद करना अच्छा नहीं लगता हैं",
            "मुझे सच में मदद करना अच्छा नहीं लगता हैं",
            "मुझे मदद की ज़रूरत नहीं हैं",
            "मुझे सच में मदद की ज़रूरत नहीं  हैं",
            "मुझे और मदद की ज़रूरत नहीं हैं",
            "मुझे  सच में और मदद की ज़रूरत नहीं हैं"
    }};

    private final String[][] layerOneSpeechEnglish = {{
            "I like to greet others and talk about my feelings",
            "I really like to greet others and talk about my feelings",
            "I want to greet others and talk about my feelings",
            "I really want to greet others and talk about my feelings",
            "I want to greet others and talk about my feelings some more",
            "I really want to greet others and talk about my feelings some more",
            "I don’t like to greet others and talk about my feelings",
            "I really don’t like to greet others and talk about my feelings",
            "I don’t want to greet others and talk about my feelings",
            "I really don’t want to greet others and talk about my feelings",
            "I don’t want to greet others and talk about my feelings anymore",
            "I really don’t want to greet others and talk about my feelings any more",
    },{"I like to do my daily activities",
            "I really like to do my daily activities",
            "I want to do my daily activities",
            "I really want to do my daily activities",
            "I want to spend more time doing my daily activities",
            "I really want to spend some more time doing my daily activities",
            "I don’t like to do my daily activities",
            "I really don’t like to do my daily activities",
            "I don’t want to do my daily activities",
            "I really don’t want to do my daily activities",
            "I don’t want to spend more time doing my daily activities",
            "I really don’t want to spend any more time doing my daily activities"
    },{"I like to eat",
            "I really like to eat",
            "I want to eat",
            "I really want to eat",
            "I want to eat some more",
            "I really want to eat some more",
            "I don’t like to eat",
            "I really don’t like to eat",
            "I don’t want to eat",
            "I really don’t want to eat",
            "I don’t want to eat any more",
            "I really don’t want to eat any more",
    },{"I like to have fun",
            "I really like to have fun",
            "I want to have fun",
            "I really want to have fun",
            "I want to have more fun",
            "I want to have some more fun",
            "I don’t like to have fun",
            "I really don’t like to have fun",
            "I don’t want to have fun",
            "I really don’t want to have fun",
            "I don’t want to have more fun",
            "I really don’t want to have any more fun"
    },{"I like to learn",
            "I really like to learn",
            "I want to learn",
            "I really want to learn",
            "I want to learn more",
            "I really want to learn some more",
            "I don’t like to learn",
            "I really don’t like to learn",
            "I don’t want to learn",
            "I really don’t want to learn",
            "I don’t want to learn any more",
            "I really don’t want to learn any more"
    },  {"I like to talk to people",
            "I really like to talk to people",
            "I want to meet people",
            "I really want to meet people",
            "I want to meet some more people",
            "I really want to meet some more people",
            "I don’t like to talk to people",
            "I really don’t like to talk to people",
            "I don’t want to meet people",
            "I really don’t want to meet people",
            "I don’t want to meet any more people",
            "I really don’t want to meet any more people"
    },{"I like to visit places",
            "I really like to visit places",
            "I want to visit different places",
            "I really want to visit different places",
            "I want to visit some more places",
            "I really want to visit some more places",
            "I don’t like to visit places",
            "I really don’t like to visit places",
            "I don’t want to visit different places",
            "I really don’t want to visit different places",
            "I don’t want to visit any more places",
            "I really don’t want to visit any more places"
    },{"I like to talk about time and weather",
            "I really like to talk about time and weather",
            "I want to talk about time and weather",
            "I really want to talk about time and weather",
            "I want to talk some more about time and weather",
            "I really want to talk some more about time and weather",
            "I don’t like to talk about time and weather",
            "I really don’t like to talk about time and weather",
            "I don’t want to talk about time and weather",
            "I really don’t want to talk about time and weather",
            "I don’t want to talk any more about time and weather",
            "I really don’t want to talk any more about time and weather"
    },{"I like to help",
            "I really like to help",
            "I need help",
            "I really need help",
            "I need more help",
            "I really need some more help",
            "I don’t like to help",
            "I really don’t like to help",
            "I don’t need help",
            "I really don’t need help",
            "I don’t need more help",
            "I really don’t need any more help"
    }};
}
