package com.dsource.idc.jellow.Models;

/**
 * Created by ekalpa on 6/22/2017.
 */

public class SequenceActivitySpeech {


    public String[][][] getSequenceActivitySpeechEnglish(){
        return sequenceActivitySpeechEnglish;
    }
    public String[][][] getSequenceActivitySpeechHindi(){
        return sequenceActivitySpeechHindi;
    }

    private final String[][][] sequenceActivitySpeechEnglish =
    {{{"I like to rinse my mouth",
            "I really like to rinse my mouth",
            "I want to rinse my mouth",
            "I really want to rinse my mouth",
            "I want to rinse my mouth some more",
            "I really want to rinse my mouth some more",
            "I don’t like to rinse my mouth",
            "I really don’t like to rinse my mouth",
            "I don’t want to rinse my mouth",
            "I really don’t want to rinse my mouth",
            "I don’t want to rinse my mouth more",
            "I really don’t want to rinse my mouth any more",

    },{"I like to rinse my toothbrush",
            "I really like to rinse my toothbrush",
            "I want to rinse my toothbrush",
            "I really want to rinse my toothbrush",
            "I want to rinse my toothbrush some more",
            "I really want to rinse my toothbrush some more",
            "I don’t like to rinse my toothbrush",
            "I really don’t like to rinse my toothbrush",
            "I don’t want to rinse my toothbrush",
            "I really don’t want to rinse my toothbrush",
            "I don’t want to rinse my toothbrush more",
            "I really don’t want to rinse my toothbrush any more"

    },{"I like to put toothpaste on my brush",
            "I really like to put toothpaste on my brush",
            "I want to put toothpaste on my brush",
            "I really want to put toothpaste on my brush",
            "I want to put some more toothpaste on my brush",
            "I really want to put some more toothpaste on my brush",
            "I don’t like to put toothpaste on my brush",
            "I really don’t like to put toothpaste on my brush",
            "I don’t want to put toothpaste on my brush",
            "I really don’t want to put toothpaste on my brush",
            "I don’t want to put more toothpaste on my brush",
            "I really don’t want to put any more toothpaste on my brush"

    },{"I like to brush my front teeth",
            "I really like to brush my front teeth",
            "I want to brush my front teeth",
            "I really want to brush my front teeth",
            "I want to brush my front teeth some more",
            "I really want to brush my front teeth some more",
            "I don’t like to brush my front teeth",
            "I really don’t like to brush my front teeth",
            "I don’t want to brush my front teeth",
            "I really don’t want to brush my front teeth",
            "I don’t want to brush my front teeth more",
            "I really don’t want to brush my front teeth any more"

    },{"I like to brush my back teeth",
            "I really like to brush my back teeth",
            "I want to brush my back teeth",
            "I really want to brush my back teeth",
            "I want to brush my back teeth some more",
            "I really want to brush my back teeth some more",
            "I don’t like to brush my back teeth",
            "I really don’t like to brush my back teeth",
            "I don’t want to brush my back teeth",
            "I really don’t want to brush my back teeth",
            "I don’t want to brush my back teeth more",
            "I really don’t want to brush my back teeth any more"

    },{"I like to brush my tongue",
            "I really like to brush my tongue",
            "I want to brush my tongue",
            "I really want to brush my tongue",
            "I want to brush my tongue some more",
            "I really want to brush my tongue some more",
            "I don’t like to brush my tongue",
            "I really don’t like to brush my tongue",
            "I don’t want to brush my tongue",
            "I really don’t want to brush my tongue",
            "I don’t want to brush my tongue more",
            "I really don’t want to brush my tongue any more",

    },{"I like to rinse my mouth",
            "I really like to rinse my mouth",
            "I want to rinse my mouth",
            "I really want to rinse my mouth",
            "I want to rinse my mouth some more",
            "I really want to rinse my mouth some more",
            "I don’t like to rinse my mouth",
            "I really don’t like to rinse my mouth",
            "I don’t want to rinse my mouth",
            "I really don’t want to rinse my mouth",
            "I don’t want to rinse my mouth more",
            "I really don’t want to rinse my mouth any more"

    }},{{
            "I have to pull my pants down",
            "I really have to pull my pants down",
            "I want to pull my pants down",
            "I really want to pull my pants down",
            "I want to pull my pants down again",
            "I really want to pull my pants down again",
            "I don’t have to pull my pants down",
            "I really don’t have to pull my pants down",
            "I don’t want to pull my pants down",
            "I really don’t want to pull my pants down",
            "I don’t want to pull my pants down again",
            "I really don’t want to pull my pants down again"

    },{"I have to sit on the toilet",
            "I really have to sit on the toilet",
            "I want to sit on the toilet",
            "I really want to sit on the toilet",
            "I want to sit on the toilet again",
            "I really want to sit on the toilet again",
            "I don’t have to sit on the toilet",
            "I really don’t have to sit on the toilet",
            "I don’t want to sit on the toilet",
            "I really don’t want to sit on the toilet",
            "I don’t want to sit on the toilet again",
            "I really don’t want to sit on the toilet again"

    },{"I have to wash my bottom",
            "I really have to wash my bottom",
            "I want to wash my bottom",
            "I really want to wash my bottom",
            "I want to wash my bottom again",
            "I really want to wash my bottom again",
            "I don’t have to wash my bottom",
            "I really don’t have to wash my bottom",
            "I don’t want to wash my bottom",
            "I really don’t want to wash my bottom",
            "I don’t want to wash my bottom again",
            "I really don’t want to wash my bottom again"

    },{"I have to flushh the toilet",
            "I really have to flushh the toilet",
            "I want to flushh the toilet",
            "I really want to flushh the toilet",
            "I want to flushh the toilet again",
            "I really want to flushh the toilet again",
            "I don’t have to flushh the toilet",
            "I really don’t have to flushh the toilet",
            "I don’t want to flushh the toilet",
            "I really don’t want to flushh the toilet",
            "I don’t want to flushh the toilet again",
            "I really don’t want to flushh the toilet again"

    },{"I have to pull my pants up",
            "I really have to pull my pants up",
            "I want to pull my pants up",
            "I really want to pull my pants up",
            "I want to pull my pants up again",
            "I really want to pull my pants up again",
            "I don’t have to pull my pants up",
            "I really don’t have to pull my pants up",
            "I don’t want to pull my pants up",
            "I really don’t want to pull my pants up",
            "I don’t want to pull my pants up again",
            "I really don’t want to pull my pants up again",

    },{"I have to wash my hands",
            "I really have to wash my hands",
            "I want to wash my hands",
            "I really want to wash my hands",
            "I want to wash my hands again",
            "I really want to wash my hands again",
            "I don’t have to wash my hands",
            "I really don’t have to wash my hands",
            "I don’t want to wash my hands",
            "I really don’t want to wash my hands",
            "I don’t want to wash my hands again",
            "I really don’t want to wash my hands again"
    }},{{"I have to remove my clothes",
            "I really have to remove my clothes",
            "I want to remove my clothes",
            "I really want to remove my clothes",
            "I want to remove my clothes again",
            "I really want to remove my clothes again",
            "I don’t have to remove my clothes",
            "I really don’t have to remove my clothes",
            "I don’t want to remove my clothes",
            "I really don’t want to remove my clothes",
            "I don’t want to remove my clothes again",
            "I really don’t want to remove my clothes again"

    },{"I have to turn on the water",
            "I really have to turn on the water",
            "I want to turn on the water",
            "I really want to turn on the water",
            "I want to turn on the water again",
            "I really want to turn on the water again",
            "I don’t have to turn on the water",
            "I really don’t have to turn on the water",
            "I don’t want to turn on the water",
            "I really don’t want to turn on the water",
            "I don’t want to turn on the water again",
            "I really don’t want to turn on the water again"

    },{"I have to get in the shower",
            "I really have to get in the shower",
            "I want to get in the shower",
            "I really want to get in the shower",
            "I want to get in the shower again",
            "I really want to get in the shower again",
            "I don’t have to get in the shower",
            "I really don’t have to get in the shower",
            "I don’t want to get in the shower",
            "I really don’t want to get in the shower",
            "I don’t want to get in the shower again",
            "I really don’t want to get in the shower again"

    },{"I like to wet my body",
            "I really like to wet my body",
            "I want to wet my body",
            "I really want to wet my body",
            "I want to wet my body again",
            "I really want to wet my body again",
            "I don’t like to wet my body",
            "I really don’t like to wet my body",
            "I don’t want to wet my body",
            "I really don’t want to wet my body",
            "I don’t want to wet my body again",
            "I really don’t want to wet my body again"

    },{"I like to put soap on my body",
            "I really like to put soap on my body",
            "I want to put soap on my body",
            "I really want to put soap on my body",
            "I want to put some more soap on my body",
            "I really want to put some more soap on my body",
            "I don’t like to put soap on my body",
            "I really don’t like to put soap on my body",
            "I don’t want to put soap on my body",
            "I really don’t want to put soap on my body",
            "I don’t want to put more soap on my body",
            "I really don’t want to put any more soap on my body"

    },{"I like to shampoo my हैर",
            "I really like to shampoo my हैर",
            "I want to shampoo my हैर",
            "I really want to shampoo my हैर",
            "I want to shampoo my हैर again",
            "I really want to shampoo my हैर again",
            "I don’t like to shampoo my हैर",
            "I really don’t like to shampoo my हैर",
            "I don’t want to shampoo my हैर",
            "I really don’t want to shampoo my हैर",
            "I don’t want to shampoo my हैर again",
            "I really don’t want to shampoo my हैर again"

    },{"I like to use face wash",
            "I really like to use face wash",
            "I want to use some face wash",
            "I really want to use some face wash",
            "I want to use face wash again",
            "I really want to use face wash again",
            "I don’t like to use face wash",
            "I really don’t like to use face wash",
            "I don’t want to use face wash",
            "I really don’t want to use face wash",
            "I don’t want to use face wash again",
            "I really don’t want to use face wash again"

    },{"I like to wash my हैर",
            "I really like to wash my हैर",
            "I want to wash my हैर",
            "I really want to wash my हैर",
            "I want to wash my हैर again",
            "I really want to wash my हैर again",
            "I don’t like to wash my हैर",
            "I really don’t like to wash my हैर",
            "I don’t want to wash my हैर",
            "I really don’t want to wash my हैर",
            "I don’t want to wash my हैर again",
            "I really don’t want to wash my हैर again"

    },{"I like to wash my body",
            "I really like to wash my body",
            "I want to wash my body",
            "I really want to wash my body",
            "I want to wash my body again",
            "I really want to wash my body again",
            "I don’t like to wash my body",
            "I really don’t like to wash my body",
            "I don’t want to wash my body",
            "I really don’t want to wash my body",
            "I don’t want to wash my body again",
            "I really don’t want to wash my body again"

    },{"I have to turn off the water",
            "I really have to turn off the water",
            "I want to turn off the water",
            "I really want to turn off the water",
            "I want to turn off the water again",
            "I really want to turn off the water again",
            "I don’t have to turn off the water",
            "I really don’t have to turn off the water",
            "I don’t want to turn off the water",
            "I really don’t want to turn off the water",
            "I don’t want to turn off the water again",
            "I really don’t want to turn off the water again"

    },{"I like to dry my हैर",
            "I really like to dry my हैर",
            "I want to dry my हैर",
            "I really want to dry my हैर",
            "I want to dry my हैर again",
            "I really want to dry my हैर again",
            "I don’t like to dry my हैर",
            "I really don’t like to dry my हैर",
            "I don’t want to dry my हैर",
            "I really don’t want to dry my हैर",
            "I don’t want to dry my हैर again",
            "I really don’t want to dry my हैर again"

    },{"I like to dry my face",
            "I really like to dry my face",
            "I want to dry my face",
            "I really want to dry my face",
            "I want to dry my face again",
            "I really want to dry my face again",
            "I don’t like to dry my face",
            "I really don’t like to dry my face",
            "I don’t want to dry my face",
            "I really don’t want to dry my face",
            "I don’t want to dry my face again",
            "I really don’t want to dry my face again",

    },{"I like to dry my body",
            "I really like to dry my body",
            "I want to dry my body",
            "I really want to dry my body",
            "I want to dry my body again",
            "I really want to dry my body again",
            "I don’t like to dry my body",
            "I really don’t like to dry my body",
            "I don’t want to dry my body",
            "I really don’t want to dry my body",
            "I don’t want to dry my body again",
            "I really don’t want to dry my body again"

    },{"I have to put my clothes on",
            "I really have to put my clothes on",
            "I want to put my clothes on",
            "I really want to put my clothes on",
            "I want to put my clothes on again",
            "I really want to put my clothes on again",
            "I don’t have to put my clothes on",
            "I really don’t have to put my clothes on",
            "I don’t want to put my clothes on",
            "I really don’t want to put my clothes on",
            "I don’t want to put my clothes on again",
            "I really don’t want to put my clothes on again"
    }},{{"I like to wake up early in the morning",
            "I really like to wake up early in the morning",
            "I want to wake up early in the morning",
            "I really want to wake up early in the morning",
            "I want to wake up early in the morning again",
            "I really want to wake up early in the morning again",
            "I don’t like to wake up early in the morning",
            "I really don’t like to wake up early in the morning",
            "I don’t want to wake up early in the morning",
            "I really don’t want to wake up early in the morning",
            "I don’t want to wake up early in the morning again",
            "I really don’t want to wake up early in the morning again"

    },{"I like to wash my face",
            "I really like to wash my face",
            "I want to wash my face",
            "I really want to wash my face",
            "I want to wash my face again",
            "I really want to wash my face again",
            "I don’t like to wash my face",
            "I really don’t like to wash my face",
            "I don’t want to wash my face",
            "I really don’t want to wash my face",
            "I don’t want to wash my face again",
            "I really don’t want to wash my face again"

    },{"I like to go to the toilet",
            "I really like to go to the toilet ",
            "I want to go to the toilet ",
            "I really want to go to the toilet ",
            "I want to go to the toilet again",
            "I really want to go to the toilet again",
            "I don’t like to go to the toilet ",
            "I really don’t like to go to the toilet ",
            "I don’t want to go to the toilet ",
            "I really don’t want to go to the toilet ",
            "I don’t want to go to the toilet again",
            "I really don’t want to go to the toilet again"

    },{"I like to brush my teeth",
            "I really like to brush my teeth",
            "I want to brush my teeth",
            "I really want to brush my teeth",
            "I want to brush my teeth again",
            "I really want to brush my teeth again",
            "I don’t like to brush my teeth",
            "I really don’t like to brush my teeth",
            "I don’t want to brush my teeth",
            "I really don’t want to brush my teeth",
            "I don’t want to brush my teeth again",
            "I really don’t want to brush my teeth again"

    },{"I have to remove my clothes",
            "I really have to remove my clothes",
            "I want to remove my clothes",
            "I really want to remove my clothes",
            "I want to remove my clothes again",
            "I really want to remove my clothes again",
            "I don’t have to remove my clothes",
            "I really don’t have to remove my clothes",
            "I don’t want to remove my clothes",
            "I really don’t want to remove my clothes",
            "I don’t want to remove my clothes again",
            "I really don’t want to remove my clothes again"

    },{"I like to bathe",
            "I really like to bathe",
            "I want to bathe",
            "I really want to bathe",
            "I want to bathe again",
            "I really want to bathe again",
            "I don’t like to bathe",
            "I really don’t like to bathe",
            "I don’t want to bathe",
            "I really don’t want to bathe",
            "I don’t want to bathe again",
            "I really don’t want to bathe again"

    },{"I like to get dressed",
            "I really like to get dressed",
            "I want to get dressed",
            "I really want to get dressed",
            "I want to get dressed again",
            "I really want to get dressed again",
            "I don’t like to get dressed",
            "I really don’t like to get dressed",
            "I don’t want to get dressed",
            "I really don’t want to get dressed",
            "I don’t want to get dressed again",
            "I really don’t want to get dressed again"

    },{"I like to comb my हैर",
            "I really like to comb my हैर",
            "I want to comb my हैर",
            "I really want to comb my हैर",
            "I want to comb my हैर again",
            "I really want to comb my हैर again",
            "I don’t like to comb my हैर",
            "I really don’t like to comb my हैर",
            "I don’t want to comb my हैर",
            "I really don’t want to comb my हैर",
            "I don’t want to comb my हैर again",
            "I really don’t want to comb my हैर again"

    },{"I like to eat brekfust",
            "I really like to eat brekfust",
            "I want to eat brekfust",
            "I really want to eat brekfust",
            "I want to eat more brekfust",
            "I really want to eat some more brekfust",
            "I don’t like to eat brekfust",
            "I really don’t like to eat brekfust",
            "I don’t want to eat brekfust",
            "I really don’t want to eat brekfust",
            "I don’t want to eat more brekfust",
            "I really don’t want to eat any more brekfust"

    },{"I like to pack my lunch box",
            "I really like to pack my lunch box",
            "I want to pack my lunch box",
            "I really want to pack my lunch box",
            "I want to pack my lunch box again",
            "I really want to pack my lunch box again",
            "I don’t like to pack my lunch box",
            "I really don’t like to pack my lunch box",
            "I don’t want to pack my lunch box",
            "I really don’t want to pack my lunch box",
            "I don’t want to pack my lunch box again",
            "I really don’t want to pack my lunch box again"

    },{"I like to pack my school bag",
            "I really like to pack my school bag",
            "I want to pack my school bag",
            "I really want to pack my school bag",
            "I want to pack my school bag again",
            "I really want to pack my school bag again",
            "I don’t like to pack my school bag",
            "I really don’t like to pack my school bag",
            "I don’t want to pack my school bag",
            "I really don’t want to pack my school bag",
            "I don’t want to pack my school bag again",
            "I really don’t want to pack my school bag again"

    },{"I like to go to school",
            "I really like to go to school",
            "I want to go to school",
            "I really want to go to school",
            "I want to go to school again",
            "I really want to go to school again",
            "I don’t like to go to school",
            "I really don’t like to go to school",
            "I don’t want to go to school",
            "I really don’t want to go to school",
            "I don’t want to go to school again",
            "I really don’t want to go to school again"

    }},{{"I like to eat dinner",
            "I really like to eat dinner",
            "I want to eat dinner",
            "I really want to eat dinner",
            "I want to eat more dinner",
            "I really want to eat some more dinner",
            "I don’t like to eat dinner",
            "I really don’t like to eat dinner",
            "I don’t want to eat dinner",
            "I really don’t want to eat dinner",
            "I don’t want to eat more dinner",
            "I really don’t want to eat any more dinner"

    },{"I like to Wear my night dress",
            "I really like to Wear my night dress",
            "I want to Wear my night dress",
            "I really want to Wear my night dress",
            "I want to Wear my night dress again",
            "I really want to Wear my night dress again",
            "I don’t like to Wear my night dress",
            "I really don’t like to Wear my night dress",
            "I don’t want to Wear my night dress",
            "I really don’t want to Wear my night dress",
            "I don’t want to Wear my night dress again",
            "I really don’t want to Wear my night dress again"

    },{"I like to brush my teeth",
            "I really like to brush my teeth",
            "I want to brush my teeth",
            "I really want to brush my teeth",
            "I want to brush my teeth again",
            "I really want to brush my teeth again",
            "I don’t like to brush my teeth",
            "I really don’t like to brush my teeth",
            "I don’t want to brush my teeth",
            "I really don’t want to brush my teeth",
            "I don’t want to brush my teeth again",
            "I really don’t want to brush my teeth again"

    },{"I like to read stories",
            "I really like to read stories",
            "I want to read a story",
            "I really want to read a story",
            "I want to read another story",
            "I really want to read another story",
            "I don’t like to read stories",
            "I really don’t like to read stories",
            "I don’t want to read a story",
            "I really don’t want to read a story",
            "I don’t want to read another story",
            "I really don’t want to read another story"

    },{"I like to say goodnight to every1",
            "I really like to say goodnight to every1",
            "I want to say goodnight to every1",
            "I really want to say goodnight to every1",
            "I want to say goodnight to every1 again",
            "I really want to say goodnight to every1 again",
            "I don’t like to say goodnight to every1",
            "I really don’t like to say goodnight to every1",
            "I don’t want to say goodnight to every1",
            "I really don’t want to say goodnight to every1",
            "I don’t want to say goodnight to every1 again",
            "I really don’t want to say goodnight to every1 again"

    },{"I like to say my prayers",
            "I really like to say my prayers",
            "I want to say my prayers",
            "I really want to say my prayers",
            "I want to say my prayers again",
            "I really want to say my prayers again",
            "I don’t like to say my prayers",
            "I really don’t like to say my prayers",
            "I don’t want to say my prayers",
            "I really don’t want to say my prayers",
            "I don’t want to say my prayers again",
            "I really don’t want to say my prayers again"
    }}};


    String[][][] sequenceActivitySpeechHindi =
    {{{"मुझे अपना मुँह पानी से धोना अच्छा लगता हैं",
            "मुझे सच में अपना मुँह पानी से धोना अच्छा लगता हैं",
            "मुझे अपना मुँह पानी से धोना हैं",
            "मुझे सच में अपना मुँह पानी से धोना हैं",
            "मुझे अपना मुँह थोड़ा और धोना हैं",
            "मुझे सच में अपना मुँह थोड़ा और धोना हैं",
            "मुझे अपना मुँह पानी से धोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना मुँह पानी से धोना अच्छा नहीं लगता हैं",
            "मुझे अपना मुँह पानी से धोना नहीं हैं",
            "मुझे सच में अपना मुँह पानी से धोना नहीं हैं",
            "मुझे अपना मुँह पानी से और नहीं धोना हैं",
            "मुझे सच में अपना मुँह पानी से और नहीं धोना हैं"

    },{"मुझे अपना टूथ ब्रश पानी से धोना अच्छा लगता हैं",
            "मुझे सच में अपना टूथ ब्रश पानी से धोना अच्छा लगता हैं",
            "मुझे अपना टूथ ब्रश पानी से धोना हैं",
            "मुझे सच में अपना टूथ ब्रश पानी से धोना हैं",
            "मुझे अपना टूथ ब्रश पानी से और धोना हैं",
            "मुझे सच में अपना टूथ ब्रश पानी से और धोना हैं",
            "मुझे अपना टूथ ब्रश पानी से धोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना टूथ ब्रश पानी से धोना अच्छा नहीं लगता हैं",
            "मुझे अपना टूथ ब्रश पानी से धोना नहीं हैं",
            "मुझे सच में अपना टूथ ब्रश पानी से धोना नहीं हैं",
            "मुझे अपना टूथ ब्रश पानी से और नहीं धोना हैं",
            "मुझे सच में अपना टूथ ब्रश पानी से और नहीं धोना हैं"

    },{"मुझे अपने ब्रश पर टूथपेस्ट लगाना अच्छा लगता हैं",
            "मुझे सच में अपने ब्रश पर टूथपेस्ट लगाना अच्छा लगता हैं",
            "मुझे अपने ब्रश पर टूथपेस्ट लगाना हैं",
            "मुझे सच में अपने ब्रश पर टूथपेस्ट लगाना हैं",
            "मुझे अपने ब्रश पर थोड़ा टूथपेस्ट लगाना हैं",
            "मुझे सच में अपने ब्रश पर बहुत टूथपेस्ट लगाना हैं",
            "मुझे अपने ब्रश पर टूथपेस्ट लगाना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने ब्रश पर टूथपेस्ट लगाना अच्छा नहीं लगता हैं",
            "मुझे अपने ब्रश पर टूथपेस्ट नहीं लगाना हैं",
            "मुझे सच में अपने ब्रश पर टूथपेस्ट नहीं लगाना हैं",
            "मुझे अपने ब्रश पर और टूथपेस्ट नहीं लगाना हैं",
            "मुझे सच में अपने ब्रश पर और टूथपेस्ट नहीं लगाना हैं"

    },{"मुझे अपने सामने के दांत साफ़ करना अच्छा लगता हैं",
            "मुझे सच में अपने सामने के दांत साफ़ करना अच्छा लगता हैं",
            "मुझे अपने सामने के दांत साफ़ करने हैं",
            "मुझे सच में अपने सामने के दांत साफ़ करने हैं",
            "मुझे अपने सामने के दांत थोड़े और साफ़ करने हैं",
            "मुझे सच में अपने सामने के दांत थोड़े और साफ़ करने हैं",
            "मुझे अपने सामने के दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने सामने के दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे अपने सामने के दांत साफ़ नहीं करने हैं",
            "मुझे सच में अपने सामने के दांत साफ़ नहीं करने हैं",
            "मुझे अपने सामने के दांत और साफ़ नहीं करने हैं",
            "मुझे सच में अपने सामने के दांत और साफ़ नहीं करने हैं"

    },{"मुझे अपने पीछे के दांत साफ़ करना अच्छा लगता हैं",
            "मुझे सच में अपने पीछे के दांत साफ़ करना अच्छा लगता हैं",
            "मुझे अपने पीछे के दांत साफ़ करने हैं",
            "मुझे सच में अपने पीछे के दांत साफ़ करने हैं",
            "मुझे अपने पीछे के दांत थोड़े और साफ़ करने हैं",
            "मुझे सच में अपने पीछे के दांत थोड़े और साफ़ करने हैं",
            "मुझे अपने पीछे के दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने पीछे के दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे अपने पीछे के दांत साफ़ नहीं करने हैं",
            "मुझे सच में अपने पीछे के दांत साफ़ नहीं करने हैं",
            "मुझे अपने पीछे के दांत और साफ़ नहीं करने हैं",
            "मुझे सच में अपने पीछे के दांत और साफ़ नहीं करने हैं"

    },{"मुझे अपनी जीभ साफ़ करना अच्छा लगता हैं",
            "मुझे सच में अपनी जीभ साफ़ करना अच्छा लगता हैं",
            "मुझे अपनी जीभ साफ़ करनी हैं",
            "मुझे सच में अपनी जीभ साफ़ करनी हैं",
            "मुझे अपनी जीभ थोड़ी और साफ़ करनी हैं",
            "मुझे सच में अपनी जीभ थोड़ी और साफ़ करनी हैं",
            "मुझे अपनी जीभ साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपनी जीभ साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे अपनी जीभ साफ़ नहीं करनी हैं",
            "मुझे सच में अपनी जीभ साफ़ नहीं करनी हैं",
            "मुझे अपनी जीभ और साफ़ नहीं करनी हैं",
            "मुझे सच में अपनी जीभ और साफ़ नहीं करनी हैं"

    },{"मुझे अपना मुँह पानी से धोना अच्छा लगता हैं",
            "मुझे सच में अपना मुँह पानी से धोना अच्छा लगता हैं",
            "मुझे अपना मुँह पानी से धोना हैं",
            "मुझे सच में अपना मुँह पानी से धोना हैं",
            "मुझे अपना मुँह थोड़ा और धोना हैं",
            "मुझे सच में अपना मुँह थोड़ा और धोना हैं",
            "मुझे अपना मुँह पानी से धोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना मुँह पानी से धोना अच्छा नहीं लगता हैं",
            "मुझे अपना मुँह पानी से धोना नहीं हैं",
            "मुझे सच में अपना मुँह पानी से धोना नहीं हैं",
            "मुझे अपना मुँह पानी से और नहीं धोना हैं",
            "मुझे सच में अपना मुँह पानी से और नहीं धोना हैं"

    }},{{"मुझे अपनी पैन्ट नीचे खींचनी हैं",
            "मुझे सच में अपनी पैन्ट नीचे खींचनी हैं",
            "मुझे अपनी पैन्ट नीचे खींचनी हैं",
            "मुझे सच में अपनी पैन्ट नीचे खींचनी हैं",
            "मुझे फिर से अपनी पैन्ट नीचे खींचनी हैं",
            "मुझे सच में फिर से अपनी पैन्ट नीचे खींचनी हैं",
            "मुझे अपनी पैन्ट नीचे नहीं खींचनी हैं",
            "मुझे सच में अपनी पैन्ट नीचे नहीं खींचनी हैं",
            "मुझे अपनी पैन्ट नीचे नहीं खींचनी हैं",
            "मुझे सच में अपनी पैन्ट नीचे नहीं खींचनी हैं",
            "मुझे फिर से अपनी पैन्ट नीचे नहीं खींचनी हैं",
            "मुझे सच में फिर से अपनी पैन्ट नीचे नहीं खींचनी हैं"

    },{"मुझे शौचालय में बैठना हैं",
            "मुझे सच में शौचालय में बैठना हैं",
            "मुझे शौचालय में बैठना हैं",
            "मुझे सच में शौचालय में बैठना हैं",
            "मुझे फिर से शौचालय में बैठना हैं",
            "मुझे सच में फिर से शौचालय में बैठना हैं",
            "मुझे शौचालय में नहीं बैठना हैं",
            "मुझे सच में शौचालय में नहीं बैठना हैं",
            "मुझे शौचालय में नहीं बैठना हैं",
            "मुझे सच में शौचालय में नहीं बैठना हैं",
            "मुझे फिर से शौचालय में नहीं बैठना हैं",
            "मुझे सच में फिर से शौचालय में नहीं बैठना हैं"

    },{"मुझे मेरा पिछला हिस्सा धोना हैं",
            "मुझे सच में मेरा पिछला हिस्सा धोना हैं",
            "मुझे मेरा पिछला हिस्सा धोना हैं",
            "मुझे सच में मेरा पिछला हिस्सा धोना हैं",
            "मुझे फिर से मेरा पिछला हिस्सा धोना हैं",
            "मुझे सच में फिर से मेरा पिछला हिस्सा धोना हैं",
            "मुझे मेरा पिछला हिस्सा नहीं धोना हैं",
            "मुझे सच में मेरा पिछला हिस्सा नहीं धोना हैं",
            "मुझे मेरा पिछला हिस्सा नहीं धोना हैं",
            "मुझे सच में मेरा पिछला हिस्सा नहीं धोना हैं",
            "मुझे फिर से मेरा पिछला हिस्सा नहीं धोना हैं",
            "मुझे सच में फिर से मेरा पिछला हिस्सा नहीं धोना हैं"

    },{"मुझे टॉयलेट फ़्लश करना हैं",
            "मुझे सच में टॉयलेट फ़्लश करना हैं",
            "मुझे टॉयलेट फ़्लश करना हैं",
            "मुझे सच में टॉयलेट फ़्लश करना हैं",
            "मुझे फिर से टॉयलेट फ़्लश करना हैं",
            "मुझे सच में फिर से टॉयलेट फ़्लश करना हैं",
            "मुझे टॉयलेट फ़्लश नहीं करना हैं",
            "मुझे सच में टॉयलेट फ़्लश नहीं करना हैं",
            "मुझे टॉयलेट फ़्लश नहीं करना हैं",
            "मुझे सच में टॉयलेट फ़्लश नहीं करना हैं",
            "मुझे फिर से टॉयलेट फ़्लश नहीं करना हैं",
            "मुझे सच में फिर से टॉयलेट फ़्लश नहीं करना हैं"

    },{"मुझे अपनी पैन्ट ऊपर खींचनी हैं",
            "मुझे सच में अपनी पैन्ट ऊपर खींचनी हैं",
            "मुझे अपनी पैन्ट ऊपर खींचनी हैं",
            "मुझे सच में अपनी पैन्ट ऊपर खींचनी हैं",
            "मुझे फिर से अपनी पैन्ट ऊपर खींचनी हैं",
            "मुझे सच में फिर से अपनी पैन्ट ऊपर खींचनी हैं",
            "मुझे अपनी पैन्ट ऊपर नहीं खींचनी हैं",
            "मुझे सच में अपनी पैन्ट ऊपर नहीं खींचनी हैं",
            "मुझे अपनी पैन्ट ऊपर नहीं खींचनी हैं",
            "मुझे सच में अपनी पैन्ट ऊपर नहीं खींचनी हैं",
            "मुझे फिर से अपनी पैन्ट ऊपर नहीं खींचनी हैं",
            "मुझे सच में फिर से अपनी पैन्ट ऊपर नहीं खींचनी हैं"

    },{"मुझे अपने हाथ धोने हैं",
            "मुझे सच में अपने हाथ धोने हैं",
            "मुझे अपने हाथ धोने हैं",
            "मुझे सच में अपने हाथ धोने हैं",
            "मुझे फिर से अपने हाथ धोने हैं",
            "मुझे सच में फिर से अपने हाथ धोने हैं",
            "मुझे अपने हाथ नहीं धोने हैं",
            "मुझे सच में अपने हाथ नहीं धोने हैं",
            "मुझे अपने हाथ नहीं धोने हैं",
            "मुझे सच में अपने हाथ नहीं धोने हैं",
            "मुझे फिर से अपने हाथ नहीं धोने हैं",
            "मुझे सच में फिर से अपने हाथ नहीं धोने हैं"

    }},{{"मुझे अपने कपड़े निकालने हैं",
            "मुझे सच में अपने कपड़े निकालने हैं",
            "मुझे अपने कपड़े निकालने हैं",
            "मुझे सच में अपने कपड़े निकालने हैं",
            "मुझे फिर से अपने कपड़े निकालने हैं",
            "मुझे सच में फिर से अपने कपड़े निकालने हैं",
            "मुझे अपने कपड़े नहीं निकालने हैं",
            "मुझे सच में अपने कपड़े नहीं निकालने हैं",
            "मुझे अपने कपड़े नहीं निकालने हैं",
            "मुझे सच में अपने कपड़े नहीं निकालने हैं",
            "मुझे फिर से अपने कपड़े नहीं निकालने हैं",
            "मुझे सच में फिर से अपने कपड़े नहीं निकालने हैं"

    },{"मुझे पानी चालू करना हैं",
            "मुझे सच में पानी चालू करना हैं",
            "मुझे पानी चालू करना हैं",
            "मुझे सच में पानी चालू करना हैं",
            "मुझे फिर से पानी चालू करना हैं",
            "मुझे सच में फिर से पानी चालू करना हैं",
            "मुझे पानी चालू नहीं करना हैं",
            "मुझे सच में पानी चालू नहीं करना हैं",
            "मुझे पानी चालू नहीं करना हैं",
            "मुझे सच में पानी चालू नहीं करना हैं",
            "मुझे फिर से पानी चालू नहीं करना हैं",
            "मुझे सच में फिर से पानी चालू नहीं करना हैं"

    },{"मुझे शॉवर लेना हैं",
            "मुझे सच में शॉवर लेना हैं",
            "मुझे शॉवर लेना हैं",
            "मुझे सच में शॉवर लेना हैं",
            "मुझे फिर से शॉवर लेना हैं",
            "मुझे सच में फिर से शॉवर लेना हैं",
            "मुझे शॉवर नहीं लेना हैं",
            "मुझे सच में शॉवर नहीं लेना हैं",
            "मुझे शॉवर नहीं लेना हैं",
            "मुझे सच में शॉवर नहीं लेना हैं",
            "मुझे फिर से शॉवर नहीं लेना हैं",
            "मुझे सच में फिर से शॉवर नहीं लेना हैं"

    },{"मुझे अपने शरीर को भिगोना अच्छा लगता हैं",
            "मुझे सच में अपने शरीर को भिगोना अच्छा लगता हैं",
            "मुझे अपने शरीर को भिगोना हैं",
            "मुझे सच में अपने शरीर को भिगोना हैं",
            "मुझे फिर से अपने शरीर को भिगोना हैं",
            "मुझे सच में फिर से अपने शरीर को भिगोना हैं",
            "मुझे अपने शरीर को भिगोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने शरीर को भिगोना अच्छा नहीं लगता हैं",
            "मुझे अपने शरीर को नहीं भिगोना हैं",
            "मुझे सच में अपने शरीर को नहीं भिगोना हैं",
            "मुझे फिर से अपने शरीर को नहीं भिगोना हैं",
            "मुझे सच में फिर से अपने शरीर को नहीं भिगोना हैं"

    },{"मुझे अपने शरीर पर साबुन लगाना अच्छा लगता हैं",
            "मुझे सच में अपने शरीर पर साबुन लगाना अच्छा लगता हैं",
            "मुझे अपने शरीर पर साबुन लगाना हैं",
            "मुझे सच में अपने शरीर पर साबुन लगाना हैं",
            "मुझे अपने शरीर पर थोड़ा और साबुन लगाना हैं",
            "मुझे सच में अपने शरीर पर थोड़ा और साबुन लगाना हैं",
            "मुझे अपने शरीर पर साबुन लगाना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने शरीर पर साबुन लगाना अच्छा नहीं लगता हैं",
            "मुझे अपने शरीर पर साबुन नहीं लगाना हैं",
            "मुझे सच में अपने शरीर पर साबुन नहीं लगाना हैं",
            "मुझे अपने शरीर पर और साबुन नहीं लगाना हैं",
            "मुझे सच में अपने शरीर पर और साबुन नहीं लगाना हैं"

    },{"मुझे अपने बालों को शाम्पू लगाना अच्छा लगता हैं",
            "मुझे सच में अपने बालों को शाम्पू लगाना अच्छा लगता हैं",
            "मुझे अपने बालों को शाम्पू लगाना हैं",
            "मुझे सच में अपने बालों को शाम्पू लगाना हैं",
            "मुझे फिर से अपने बालों को शाम्पू लगाना हैं",
            "मुझे सच में फिर से अपने बालों को शाम्पू लगाना हैं",
            "मुझे अपने बालों को शाम्पू लगाना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने बालों को शाम्पू लगाना अच्छा नहीं लगता हैं",
            "मुझे अपने बालों को शाम्पू नहीं लगाना हैं",
            "मुझे सच में अपने बालों को शाम्पू नहीं लगाना हैं",
            "मुझे फिर से अपने बालों को शाम्पू नहीं लगाना हैं",
            "मुझे सच में फिर से अपने बालों को शाम्पू नहीं लगाना हैं"

    },{"मुझे फेस वॉश का इस्तमाल करना अच्छा लगता हैं",
            "मुझे सच में फेस वॉश का इस्तमाल करना अच्छा लगता हैं",
            "मुझे फेस वॉश का इस्तमाल करना हैं",
            "मुझे सच में फेस वॉश का इस्तमाल करना हैं",
            "मुझे फिर से फेस वॉश का इस्तमाल करना हैं",
            "मुझे सच में फिर से फेस वॉश का इस्तमाल करना हैं",
            "मुझे फेस वॉश का इस्तमाल करना अच्छा नहीं लगता हैं",
            "मुझे सच में फेस वॉश का इस्तमाल करना अच्छा नहीं लगता हैं",
            "मुझे फेस वॉश का इस्तमाल नहीं करना हैं",
            "मुझे सच में फेस वॉश का इस्तमाल नहीं करना हैं",
            "मुझे फिर से फेस वॉश का इस्तमाल नहीं करना हैं",
            "मुझे सच में फिर से फेस वॉश का इस्तमाल नहीं करना हैं"

    },{"मुझे अपने बाल धोना अच्छा लगता हैं",
            "मुझे सच में अपने बाल धोना अच्छा लगता हैं",
            "मुझे अपने बाल धोने हैं",
            "मुझे सच में अपने बाल धोने हैं",
            "मुझे फिर से अपने बाल धोने हैं",
            "मुझे सच में फिर से अपने बाल धोने हैं",
            "मुझे अपने बाल धोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने बाल धोना अच्छा नहीं लगता हैं",
            "मुझे अपने बाल नहीं धोने हैं",
            "मुझे सच में अपने बाल नहीं धोने हैं",
            "मुझे फिर से अपने बाल नहीं धोने हैं",
            "मुझे सच में फिर से अपने बाल नहीं धोने हैं"

    },{"मुझे अपना शरीर धोना अच्छा लगता हैं",
            "मुझे सच में अपना शरीर धोना अच्छा लगता हैं",
            "मुझे अपना शरीर धोना हैं",
            "मुझे सच में अपना शरीर धोना हैं",
            "मुझे फिर से अपना शरीर धोना हैं",
            "मुझे सच में फिर से अपना शरीर धोना हैं",
            "मुझे अपना शरीर धोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना शरीर धोना अच्छा नहीं लगता हैं",
            "मुझे अपना शरीर नहीं धोना हैं",
            "मुझे सच में अपना शरीर नहीं धोना हैं",
            "मुझे फिर से अपना शरीर नहीं धोना हैं",
            "मुझे सच में फिर से अपना शरीर नहीं धोना हैं"

    },{"मुझे पानी बंद करना हैं",
            "मुझे सच में पानी बंद करना हैं",
            "मुझे पानी बंद करना हैं",
            "मुझे सच में पानी बंद करना हैं",
            "मुझे फिर से पानी बंद करना हैं",
            "मुझे सच में फिर से पानी बंद करना हैं",
            "मुझे पानी बंद नहीं करना हैं",
            "मुझे सच में पानी बंद नहीं करना हैं",
            "मुझे पानी बंद नहीं करना हैं",
            "मुझे सच में पानी बंद नहीं करना हैं",
            "मुझे फिर से पानी बंद नहीं करना हैं",
            "मुझे सच में फिर से पानी बंद नहीं करना हैं"

    },{"मुझे अपने बाल सुखाना अच्छा लगता हैं",
            "मुझे सच में अपने बाल सुखाना अच्छा लगता हैं",
            "मुझे अपने बाल सुखाने हैं",
            "मुझे सच में अपने बाल सुखाने हैं",
            "मुझे फिर से अपने बाल सुखाने हैं",
            "मुझे सच में फिर से अपने बाल सुखाने हैं",
            "मुझे अपने बाल सुखाना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने बाल सुखाना अच्छा नहीं लगता हैं",
            "मुझे अपने बाल नहीं सुखाने हैं",
            "मुझे सच में अपने बाल नहीं सुखाने हैं",
            "मुझे फिर से अपने बाल नहीं सुखाने हैं",
            "मुझे सच में फिर से अपने बाल नहीं सुखाने हैं"

    },{"मुझे अपना चेहरा पोंछना अच्छा लगता हैं",
            "मुझे सच में अपना चेहरा पोंछना अच्छा लगता हैं",
            "मुझे अपना चेहरा पोंछना हैं",
            "मुझे सच में अपना चेहरा पोंछना हैं",
            "मुझे फिर से अपना चेहरा पोंछना हैं",
            "मुझे सच में फिर से अपना चेहरा पोंछना हैं",
            "मुझे अपना चेहरा पोंछना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना चेहरा पोंछना अच्छा नहीं लगता हैं",
            "मुझे अपना चेहरा नहीं पोंछना हैं",
            "मुझे सच में अपना चेहरा नहीं पोंछना हैं",
            "मुझे फिर से अपना चेहरा नहीं पोंछना हैं",
            "मुझे सच में फिर से अपना चेहरा नहीं पोंछना हैं"

    },{"मुझे अपना शरीर पोंछना अच्छा लगता हैं",
            "मुझे सच में अपना शरीर पोंछना अच्छा लगता हैं",
            "मुझे अपना शरीर पोंछना हैं",
            "मुझे सच में अपना शरीर पोंछना हैं",
            "मुझे फिर से अपना शरीर पोंछना हैं",
            "मुझे सच में फिर से अपना शरीर पोंछना हैं",
            "मुझे अपना शरीर पोंछना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना शरीर पोंछना अच्छा नहीं लगता हैं",
            "मुझे अपना शरीर नहीं पोंछना हैं",
            "मुझे सच में अपना शरीर नहीं पोंछना हैं",
            "मुझे फिर से अपना शरीर नहीं पोंछना हैं",
            "मुझे सच में फिर से अपना शरीर नहीं पोंछना हैं"

    },{"मुझे अपने कपड़े पहनने हैं",
            "मुझे सच में अपने कपड़े पहनने हैं",
            "मुझे अपने कपड़े पहनने हैं",
            "मुझे सच में अपने कपड़े पहनने हैं",
            "मुझे अपने कपड़े फिर से पहनने हैं",
            "मुझे सच में अपने कपड़े फिर से पहनने हैं",
            "मुझे अपने कपड़े नहीं पहनने हैं",
            "मुझे सच में अपने कपड़े नहीं पहनने हैं",
            "मुझे अपने कपड़े नहीं पहनने हैं",
            "मुझे सच में अपने कपड़े नहीं पहनने हैं",
            "मुझे अपने कपड़े फिर से नहीं पहनने हैं",
            "मुझे सच में अपने कपड़े फिर से नहीं पहनने हैं"

    }},{{"मुझे सुबह जल्दी उठना अच्छा लगता हैं",
            "मुझे सच में सुबह जल्दी उठना अच्छा लगता हैं",
            "मुझे सुबह जल्दी उठना हैं",
            "मुझे सच में सुबह जल्दी उठना हैं",
            "मुझे फिर से सुबह जल्दी उठना हैं",
            "मुझे सच में फिर से सुबह जल्दी उठना हैं",
            "मुझे सुबह जल्दी उठना अच्छा नहीं लगता हैं",
            "मुझे सच में सुबह जल्दी उठना अच्छा नहीं लगता हैं",
            "मुझे सुबह जल्दी नहीं उठना हैं",
            "मुझे सच में सुबह जल्दी नहीं उठना हैं",
            "मुझे फिर से सुबह जल्दी नहीं उठना हैं",
            "मुझे सच में फिर से सुबह जल्दी नहीं उठना हैं",

    },{"मुझे अपना चेहरा धोना अच्छा लगता हैं",
            "मुझे सच में अपना चेहरा धोना अच्छा लगता हैं",
            "मुझे अपना चेहरा धोना हैं",
            "मुझे सच में अपना चेहरा धोना हैं",
            "मुझे फिर से अपना चेहरा धोना हैं",
            "मुझे सच में फिर से अपना चेहरा धोना हैं",
            "मुझे अपना चेहरा धोना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना चेहरा धोना अच्छा नहीं लगता हैं",
            "मुझे अपना चेहरा नहीं धोना हैं",
            "मुझे सच में अपना चेहरा नहीं धोना हैं",
            "मुझे फिर से अपना चेहरा नहीं धोना हैं",
            "मुझे सच में फिर से अपना चेहरा नहीं धोना हैं"

    },{"मुझे शौचालय जाना अच्छा लगता हैं",
            "मुझे सच में शौचालय जाना अच्छा लगता हैं",
            "मुझे शौचा लय जाना हैं",
            "मुझे सच में शौचालय जाना हैं",
            "मुझे फिर से शौचालय जाना हैं",
            "मुझे सच में फिर से शौचालय जाना हैं",
            "मुझे शौचालय जाना अच्छा नहीं लगता हैं",
            "मुझे सच में शौचालय जाना अच्छा नहीं लगता हैं",
            "मुझे शौचालय नहीं जाना हैं",
            "मुझे सच में शौचालय नहीं जाना हैं",
            "मुझे फिर से शौचालय नहीं जाना हैं",
            "मुझे सच में फिर से शौचालय नहीं जाना हैं"

    },{"मुझे अपने दांत साफ़ करना अच्छा लगता हैं",
            "मुझे सच में अपने दांत साफ़ करना अच्छा लगता हैं",
            "मुझे अपने दांत साफ़ करने हैं",
            "मुझे सच में अपने दांत साफ़ करने हैं",
            "मुझे फिर से अपने दांत साफ़ करने हैं",
            "मुझे सच में फिर से अपने दांत साफ़ करने हैं",
            "मुझे अपने दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे अपने दांत साफ़ नहीं करने हैं",
            "मुझे सच में अपने दांत साफ़ नहीं करने हैं",
            "मुझे फिर से अपने दांत साफ़ नहीं करने हैं",
            "मुझे सच में फिर से अपने दांत साफ़ नहीं करने हैं"

    },{"मुझे अपने कपड़े उतारना अच्छा लगता हैं",
            "मुझे सच में अपने कपड़े उतारना अच्छा लगता हैं",
            "मुझे अपने कपड़े उतारने हैं",
            "मुझे सच में अपने कपड़े उतारने हैं",
            "मुझे फिर से अपने कपड़े उतारने हैं",
            "मुझे सच में फिर से अपने कपड़े उतारने हैं",
            "मुझे अपने कपड़े उतारना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने कपड़े उतारना अच्छा नहीं लगता हैं",
            "मुझे अपने कपड़े नहीं उतारने हैं",
            "मुझे सच में अपने कपड़े नहीं उतारने हैं",
            "मुझे फिर से अपने कपड़े नहीं उतारने हैं",
            "मुझे सच में फिर से अपने कपड़े नहीं उतारने हैं"

    },{"मुझे नहाना अच्छा लगता हैं",
            "मुझे सच में नहाना अच्छा लगता हैं",
            "मुझे नहाना हैं",
            "मुझे सच में नहाना हैं",
            "मुझे फिर से नहाना हैं",
            "मुझे सच में फिर से नहाना हैं",
            "मुझे नहाना अच्छा नहीं लगता हैं",
            "मुझे सच में नहाना अच्छा नहीं लगता हैं",
            "मुझे नहाना नहीं हैं",
            "मुझे सच में नहाना नहीं हैं",
            "मुझे फिर से नहाना नहीं हैं",
            "मुझे सच में फिर से नहाना नहीं हैं"

    },{"मुझे कपड़े पहनने हैं",
            "मुझे सच में कपड़े पहनने हैं",
            "मुझे कपड़े पहनने हैं",
            "मुझे सच में कपड़े पहनने हैं",
            "मुझे फिर से कपड़े पहनने हैं",
            "मुझे सच में फिर से कपड़े पहनने हैं",
            "मुझे कपड़े नहीं पहनने हैं",
            "मुझे सच में कपड़े नहीं पहनने हैं",
            "मुझे कपड़े नहीं पहनने हैं",
            "मुझे सच में कपड़े नहीं पहनने हैं",
            "मुझे फिर से कपड़े नहीं पहनने हैं",
            "मुझे सच में फिर से कपड़े नहीं पहनने हैं"

    },{"मुझे अपने बालों को कंघी करना अच्छा लगता हैं",
            "मुझे सच में अपने बालों को कंघी करना अच्छा लगता हैं",
            "मुझे अपने बालों को कंघी करनी हैं",
            "मुझे सच में अपने बालों को कंघी करनी हैं",
            "मुझे फिर से अपने बालों को कंघी करनी हैं",
            "मुझे सच में फिर से अपने बालों को कंघी करनी हैं",
            "मुझे अपने बालों को कंघी करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने बालों को कंघी करना अच्छा नहीं लगता हैं",
            "मुझे अपने बालों को कंघी नहीं करनी हैं",
            "मुझे सच में अपने बालों को कंघी नहीं करनी हैं",
            "मुझे फिर से अपने बालों को कंघी नहीं करनी हैं",
            "मुझे सच में फिर से अपने बालों को कंघी नहीं करनी हैं"

    },{"मुझे सुबह का नाश्ता करना अच्छा लगता हैं",
            "मुझे सच में सुबह का नाश्ता करना अच्छा लगता हैं",
            "मुझे सुबह का नाश्ता चाहिए",
            "मुझे सच में सुबह का नाश्ता चाहिए",
            "मुझे थोड़ा और नाश्ता चाहिए",
            "मुझे सच में थोड़ा और नाश्ता चाहिए",
            "मुझे सुबह का नाश्ता करना अच्छा नहीं लगता हैं",
            "मुझे सच में सुबह का नाश्ता करना अच्छा नहीं लगता हैं",
            "मुझे सुबह का नाश्ता नहीं चाहिए",
            "मुझे सच में सुबह का नाश्ता नहीं चाहिए",
            "मुझे और नाश्ता नहीं चाहिए",
            "मुझे सच में कुछ भी नाश्ता नहीं चाहिए"

    },{"मुझे अपना खाने का डिब्बा भरना अच्छा लगता हैं",
            "मुझे सच में अपना खाने का डिब्बा भरना अच्छा लगता हैं",
            "मुझे अपने खाने का डिब्बा भरना हैं",
            "मुझे सच में अपने खाने का डिब्बा भरना हैं",
            "मुझे फिर से अपने खाने का डिब्बा भरना हैं",
            "मुझे सच में फिर से अपने खाने का डिब्बा भरना हैं",
            "मुझे अपना खाने का डिब्बा भरना अच्छा नहीं लगता हैं",
            "मुझे सच में अपना खाने का डिब्बा भरना अच्छा नहीं लगता हैं",
            "मुझे अपने खाने का डिब्बा नहीं भरना हैं",
            "मुझे सच में अपने खाने का डिब्बा नहीं भरना हैं",
            "मुझे फिर से अपने खाने का डिब्बा नहीं भरना हैं",
            "मुझे सच में फिर से अपने खाने का डिब्बा नहीं भरना हैं"

    },{"मुझे अपनी पाठशाला की bag भरना अच्छा लगता हैं",
            "मुझे सच में अपनी पाठशाला की bag भरना अच्छा लगता हैं",
            "मुझे अपनी पाठशाला की bag भरनी हैं",
            "मुझे सच में अपनी पाठशाला की bag भरनी हैं",
            "मुझे फिर से अपनी पाठशाला की bag भरनी हैं",
            "मुझे सच में फिर से अपनी पाठशाला की bag भरनी हैं",
            "मुझे अपनी पाठशाला की bag भरना अच्छा नहीं लगता हैं",
            "मुझे सच में अपनी पाठशाला की bag भरना अच्छा नहीं लगता हैं",
            "मुझे अपनी पाठशाला की bag नहीं भरनी हैं",
            "मुझे सच में अपनी पाठशाला की bag नहीं भरनी हैं",
            "मुझे फिर से अपनी पाठशाला की bag नहीं भरनी हैं",
            "मुझे सच में फिर से अपनी पाठशाला की bag नहीं भरनी हैं"

    },{"मुझे पाठशाला जाना अच्छा लगता हैं",
            "मुझे सच में पाठशाला जाना अच्छा लगता हैं",
            "मुझे पाठशाला जाना हैं",
            "मुझे सच में पाठशाला जाना हैं",
            "मुझे फिर से पाठशाला जाना हैं",
            "मुझे सच में फिर से पाठशाला जाना हैं",
            "मुझे पाठशाला जाना अच्छा नहीं लगता हैं",
            "मुझे सच में पाठशाला जाना अच्छा नहीं लगता हैं",
            "मुझे पाठशाला नहीं जाना हैं",
            "मुझे सच में पाठशाला नहीं जाना हैं",
            "मुझे फिर से पाठशाला नहीं जाना हैं",
            "मुझे सच में फिर से पाठशाला नहीं जाना हैं"

    }},{{"मुझे रात का भोजन करना अच्छा लगता हैं",
            "मुझे सच में रात का भोजन करना अच्छा लगता हैं",
            "मुझे रात का भोजन चाहिए",
            "मुझे सच में रात का भोजन चाहिए",
            "मुझे और भोजन चाहिए",
            "मुझे सच में और भोजन चाहिए",
            "मुझे रात का भोजन करना अच्छा नहीं लगता हैं",
            "मुझे सच में रात का भोजन करना अच्छा नहीं लगता हैं",
            "मुझे रात  का भोजन नहीं चाहिए",
            "मुझे सच में रात  का भोजन नहीं चाहिए",
            "मुझे और भोजन नहीं चाहिए",
            "मुझे सच में और भोजन नहीं चाहिए"

    },{"मुझे रात के कपड़े पैहनना अच्छा लगता हैं",
            "मुझे सच में रात के कपड़े पैहनना अच्छा लगता हैं",
            "मुझे रात के कपड़े पहनने हैं",
            "मुझे सच में रात के कपड़े पहनने हैं",
            "मुझे फिर से रात के कपड़े पहनने हैं",
            "मुझे सच में फिर से रात के कपड़े पहनने हैं",
            "मुझे रात के कपड़े पैहनना अच्छा नहीं लगता हैं",
            "मुझे सच में रात के कपड़े पैहनना अच्छा नहीं लगता हैं",
            "मुझे रात के कपड़े नहीं पहनने हैं",
            "मुझे सच में रात के कपड़े नहीं पहनने हैं",
            "मुझे फिर से रात के कपड़े नहीं पहनने हैं",
            "मुझे सच में फिर से रात के कपड़े नहीं पहनने हैं"

    },{"मुझे अपने दांत साफ़ करना अच्छा लगता हैं",
            "मुझे सच में अपने दांत साफ़ करना अच्छा लगता हैं",
            "मुझे अपने दांत साफ़ करने हैं",
            "मुझे सच में अपने दांत साफ़ करने हैं",
            "मुझे फिर से अपने दांत साफ़ करने हैं",
            "मुझे सच में फिर से अपने दांत साफ़ करने हैं",
            "मुझे अपने दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे सच में अपने दांत साफ़ करना अच्छा नहीं लगता हैं",
            "मुझे अपने दांत साफ़ नहीं करने हैं",
            "मुझे सच में अपने दांत साफ़ नहीं करने हैं",
            "मुझे फिर से अपने दांत साफ़ नहीं करने हैं",
            "मुझे सच में फिर से अपने दांत साफ़ नहीं करने हैं"

    },{"मुझे कहानियाँ पढ़ना अच्छा लगता हैं",
            "मुझे सच में कहानियाँ पढ़ना अच्छा लगता हैं",
            "मुझे एक कहानी पढ़नी हैं",
            "मुझे सच में एक कहानी पढ़नी हैं",
            "मुझे और एक कहानी पढ़नी हैं",
            "मुझे सच में और एक कहानी पढ़नी हैं",
            "मुझे कहानियाँ पढ़ना अच्छा नहीं लगता हैं",
            "मुझे सच में कहानियाँ पढ़ना अच्छा नहीं लगता हैं",
            "मुझे कहानी नहीं पढ़नी हैं",
            "मुझे सच में कहानी नहीं पढ़नी हैं",
            "मुझे और एक कहानी नहीं पढ़नी हैं",
            "मुझे सच में और एक कहानी नहीं पढ़नी हैं"

    },{"मुझे सबको शुभ रात्रि बोलना अच्छा लगता हैं",
            "मुझे सच में सबको शुभ रात्रि बोलना अच्छा लगता हैं",
            "मुझे सबको शुभ रात्रि बोलना हैं",
            "मुझे सच में सबको शुभ रात्रि बोलना हैं",
            "मुझे फिर से सबको शुभ रात्रि बोलना हैं",
            "मुझे सच में फिर से सबको शुभ रात्रि बोलना हैं",
            "मुझे सबको शुभ रात्रि बोलना अच्छा नहीं लगता हैं",
            "मुझे सच में सबको शुभ रात्रि बोलना अच्छा नहीं लगता हैं",
            "मुझे सबको शुभ रात्रि नहीं बोलना हैं",
            "मुझे सच में सबको शुभ रात्रि नहीं बोलना हैं",
            "मुझे फिर से सबको शुभ रात्रि नहीं बोलना हैं",
            "मुझे सच में फिर से सबको शुभ रात्रि नहीं बोलना हैं"

    },{"मुझे प्रार्थना करना अच्छा लगता हैं",
            "मुझे सच में प्रार्थना करना अच्छा लगता हैं",
            "मुझे प्रार्थना करनी हैं",
            "मुझे सच में प्रार्थना करनी हैं",
            "मुझे फिर से प्रार्थना करनी हैं",
            "मुझे सच में फिर से प्रार्थना करनी हैं",
            "मुझे प्रार्थना करना अच्छा नहीं लगता हैं",
            "मुझे सच में प्रार्थना करना अच्छा नहीं लगता हैं",
            "मुझे प्रार्थना नहीं करनी हैं",
            "मुझे सच में प्रार्थना नहीं करनी हैं",
            "मुझे फिर से प्रार्थना नहीं करनी हैं",
            "मुझे सच में फिर से प्रार्थना नहीं करनी हैं",
    }}};
}